### ISSUE TITLE
For `findMany`, when matching to multiple where criteria (using `OR`), it fails

### ISSUE THREAD

**Issue by PDSpotter** [morintd/prismock#1034]
We have a function that includes an `OR` matching, like the following:
```ts
prismaClient.model.findMany({
  where: {
    AND: [{
      OR: [
        {
          field: {
            contains: 'value',
            mode: 'insensitive',
          }
        },
        {
          field2: {
            contains: 'value',
            mode: 'insensitive',
          }
        },
        {
          field3: {
            contains: 'value',
            mode: 'insensitive',
          }
        },
        // ...
      ]
    }]
  }
});
```

Will fail with the following error:

```ts
      Error in myCall: TypeError: Cannot read properties of null (reading 'indexOf')
          at match (/Users/user/Documents/Development/my-project/node_modules/.pnpm/prismock@1.31.3_@prisma+client@5.17.0/node_modules/prismock/src/lib/operations/find/match.ts:148:23)
          at matchMultiple (/Users/user/Documents/Development/my-project/node_modules/.pnpm/prismock@1.31.3_@prisma+client@5.17.0/node_modules/prismock/src/lib/operations/find/match.ts:180:10)
          at /Users/user/Documents/Development/my-project/node_modules/.pnpm/prismock@1.31.3_@prisma+client@5.17.0/node_modules/prismock/src/lib/operations/find/match.ts:31:47
          at Array.some (<anonymous>)
          at matchOr (/Users/user/Documents/Development/my-project/node_modules/.pnpm/prismock@1.31.3_@prisma+client@5.17.0/node_modules/prismock/src/lib/operations/find/match.ts:31:18)
          at match (/Users/user/Documents/Development/my-project/node_modules/.pnpm/prismock@1.31.3_@prisma+client@5.17.0/node_modules/prismock/src/lib/operations/find/match.ts:47:32)
          at matchMultiple (/Users/user/Documents/Development/my-project/node_modules/.pnpm/prismock@1.31.3_@prisma+client@5.17.0/node_modules/prismock/src/lib/operations/find/match.ts:180:10)
          at /Users/user/Documents/Development/my-project/node_modules/.pnpm/prismock@1.31.3_@prisma+client@5.17.0/node_modules/prismock/src/lib/operations/find/match.ts:27:49
          at Array.filter (<anonymous>)
          at matchAnd (/Users/user/Documents/Development/my-project/node_modules/.pnpm/prismock@1.31.3_@prisma+client@5.17.0/node_modules/prismock/src/lib/operations/find/match.ts:27:18)
          at match (/Users/user/Documents/Development/my-project/node_modules/.pnpm/prismock@1.31.3_@prisma+client@5.17.0/node_modules/prismock/src/lib/operations/find/match.ts:48:33)
          at matchMultiple (/Users/user/Documents/Development/my-project/node_modules/.pnpm/prismock@1.31.3_@prisma+client@5.17.0/node_modules/prismock/src/lib/operations/find/match.ts:180:10)
          at /Users/user/Documents/Development/my-project/node_modules/.pnpm/prismock@1.31.3_@prisma+client@5.17.0/node_modules/prismock/src/lib/operations/find/find.ts:32:58
          at /Users/user/Documents/Development/my-project/node_modules/.pnpm/prismock@1.31.3_@prisma+client@5.17.0/node_modules/prismock/src/lib/operations/find/find.ts:259:84
          at Array.filter (<anonymous>)
          at /Users/user/Documents/Development/my-project/node_modules/.pnpm/prismock@1.31.3_@prisma+client@5.17.0/node_modules/prismock/src/lib/operations/find/find.ts:259:30
          at /Users/user/Documents/Development/my-project/node_modules/.pnpm/prismock@1.31.3_@prisma+client@5.17.0/node_modules/prismock/src/lib/helpers.ts:61:14
          at Array.reduce (<anonymous>)
          at /Users/user/Documents/Development/my-project/node_modules/.pnpm/prismock@1.31.3_@prisma+client@5.17.0/node_modules/prismock/src/lib/helpers.ts:60:22
          at findMany (/Users/user/Documents/Development/my-project/node_modules/.pnpm/prismock@1.31.3_@prisma+client@5.17.0/node_modules/prismock/src/lib/operations/find/find.ts:263:4)
          at Object.findMany (/Users/user/Documents/Development/my-project/node_modules/.pnpm/prismock@1.31.3_@prisma+client@5.17.0/node_modules/prismock/src/lib/delegate.ts:93:38)
```

**Comment by morintd** [comment]
Hello @PabloDoradoSpotter , I was unable to reproduce your issue as shown in the added test from https://github.com/morintd/prismock/pull/1064. If you have a different use-case, please let me know.

You can also either add a test yourself or open a public repo where I can reproduce this issue.
